### ISSUE TITLE
自定义tags功能

### ISSUE THREAD

**Issue by Yakumo-Yukari** [hhandhuan/ku-bbs#1]
![2022-07-23 070613](https://user-images.githubusercontent.com/12076232/180579175-78360632-a31c-4cb0-9b04-10351ca5b726.png)

能否在发帖时用户可以自定义帖子的tags 如图

**Comment by hhandhuan** [comment]
可以考虑后面加入自定义Tag @Yakumo-Yukari

**Comment by hhandhuan** [comment]
已完成 目前没有校验参数  @Yakumo-Yukari

**Comment by Yakumo-Yukari** [comment]
> 已完成 目前没有校验参数 @Yakumo-Yukari

好的   ，大佬有Q群吗  单独加你需要验证

**Comment by hhandhuan** [comment]
@Yakumo-Yukari  验证随便填呢。

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 验证随便填呢。

会提示错误

**Comment by hhandhuan** [comment]
> 

在试试

**Comment by hhandhuan** [comment]
@Yakumo-Yukari 在试试

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 在试试

可以了
