### ISSUE TITLE
大佬assets下的a u目录代表的是什么呢？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [hhandhuan/ku-bbs#2]
emmm，为什么使用这样的命名方式呢？感觉看得有点懵呀？

**Comment by hhandhuan** [comment]
a 是静态资源 u 是用户自定义上传资源目录

**Comment by Yakumo-Yukari** [comment]
> a 是静态资源 u 是用户自定义上传资源目录

emmm 怎么不直接用 Static  Upload呢？  感觉用单字母用起来怪怪的  也不易于理解，我开始看目录看了半天也没能理解到 噗

**Comment by hhandhuan** [comment]
@hhandhuan 哈喽可以加我qq讨论吗 915664508

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 哈喽可以加我qq讨论吗 915664508

好的
