### ISSUE TITLE
我在 nodes创建了一个话题，我发布时选择了此话题，但是首页展示不出来，只在我的帖子中可以看到

### ISSUE THREAD

**Issue by zyl-fun** [hhandhuan/ku-bbs#3]
![image](https://user-images.githubusercontent.com/67250125/181436799-ab0e6efa-e4dd-4584-b660-2fdf12d06a7c.png)
![image](https://user-images.githubusercontent.com/67250125/181436876-5aa4db85-85fb-4ac4-a5a0-88223dd4f209.png)

**Comment by zyl-fun** [comment]
![image](https://user-images.githubusercontent.com/67250125/181437019-7c4416b3-6218-4839-826c-c9442636a4c2.png)

**Comment by hhandhuan** [comment]
我本地测试没有问题 可以贴下数据结构 @zyl-fun

**Comment by zyl-fun** [comment]
![image](https://user-images.githubusercontent.com/67250125/181438960-bcb0c5b0-8446-4a37-af94-b24ef71d39db.png)
nodes表中没数据，需要手动添加吗？

**Comment by hhandhuan** [comment]
nodes 数据需要手动加。我贴下我本地数据

<img width="734" alt="image" src="https://user-images.githubusercontent.com/95403191/181439287-b080705e-0220-4531-9dc8-a3b266022667.png">

其次在发布话题的时候需要选择话题

**Comment by zyl-fun** [comment]
@hhandhuan 请问还有其它需要手动添加数据的表吗？

**Comment by hhandhuan** [comment]
@zyl-fun 不需要了，用户表还有两个字段我忘记更新了 稍等我提交下

**Comment by zyl-fun** [comment]
![image](https://user-images.githubusercontent.com/67250125/181440982-49068520-9452-4303-9049-6390f1efa639.png)

**Comment by zyl-fun** [comment]
![image](https://user-images.githubusercontent.com/67250125/181441162-ba2dd2ed-39f6-49e5-8622-bf04925d8bd9.png)
还是无数据首页

**Comment by hhandhuan** [comment]
@zyl-fun qq 915664508 加我

**Comment by zyl-fun** [comment]
ok
